const express=require("express");
const router=express.Router();
const {signUp,login,refresh,logOut}=require("../Controller/User");
const authenticator=require("../MiddleWares/auth"); 
const unexpectedHandler=require("../utils/errorHandler.js");
const asyncHandler=require("../utils/asyncHandler");
router.post("/signUp",asyncHandler(signUp),unexpectedHandler);
 router.post("/login",login);
router.post("/refresh",refresh);
  router.get("/logOut",authenticator,logOut);
 module.exports=router;
